name: Dark's Site
description: Software Developer
url: https://darkhax-forked.github.io
baseurl: '/jekyll-clean-dark'

author: Tyler Hancock
copyright: 2011-2018

share:
  facebook: false
  twitter: true
  gplus: false
  linkedin: false
  pinterest: false
  email: false
  stackoverflow: false
  instagram: false
  lastfm: false

social:
  github: darkhax
  twitter: DarkhaxDev
  rss: feed.xml

# Stuff to ignore
google_analytics_key:
yandex_metrica:
disqus: streetturtle
comments: false

permalink: /:year/:month/:title

# Enable for using pages, more details are here: http://jekyllrb.com/docs/pagination/
#paginate: 3

#highlighter: rouge

markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  hard_wrap: true

exclude: ['README.md', 'LICENSE']
