name: Dark's Site
description: Software Developer
url: http://darkhax.github.io/
baseurl: ''

author: Tyler Hancock
copyright: 2011-2019

share:
  facebook: false
  twitter: true
  gplus: false
  linkedin: false
  pinterest: false
  email: false
  stackoverflow: false
  instagram: false
  lastfm: false

social:
  github: darkhax
  twitter: DarkhaxDev
  rss: feed.xml

# Stuff to ignore
google_analytics_key: "UA-51262738-1"
yandex_metrica:
disqus: streetturtle
comments: false

permalink: /:year/:month/:title

# Enable for using pages, more details are here: http://jekyllrb.com/docs/pagination/
#paginate: 3

#highlighter: rouge

markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  hard_wrap: true

exclude: ['README.md', 'LICENSE']
